apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: test-
spec:
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/scoheb/test-stepactions
      - name: revision
        value: main
      - name: pathInRepo
        value: debug/collect-data-task.yaml
