apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-plr
spec:
  PipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/scoheb/test-stepactions
      - name: revision
        value: main
      - name: pathInRepo
        value: without-stepsresults/pipeline.yaml
