---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  generateName: test-pipeline
spec:
  tasks:
    - name: collect-data
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/scoheb/test-stepactions
          - name: revision
            value: main
          - name: pathInRepo
            value: git-referenced/collect-data-task.yaml
    - name: apply-data
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/scoheb/test-stepactions
          - name: revision
            value: main
          - name: pathInRepo
            value: git-referenced/apply-data-task.yaml
      params:
        - name: resultsDir
          value: "$(tasks.collect-data.resultsDir.data)"
