kind: ResourceQuota
apiVersion: v1
metadata:
  name: compute-build
  namespace: default
spec:
  hard:
    limits.cpu: '1'
    limits.memory: 1Gi
    requests.cpu: '1'
    requests.memory: 1Gi
  scopes:
    - Terminating
