---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: step1
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      env:
        - name: pyxisCert
          valueFrom:
            secretKeyRef:
              name: pyxiscert
              key: cert
      script: |
        #!/usr/bin/env sh
        set -x
        echo "hello world"
